import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nunito } from 'next/font/google';
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-nunito',
});


export const metadata: Metadata = {
  title: "Puja's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" className={nunito.className}>
      <body>
        <Navbar />
        <Header/>
        {children}
      </body>
    </html>
  );
}
